{% set name = "physical_validation" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shirtsgroup/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 166625feaadbd1cea8cdfda017b8b050ece751b8fe205ffbad0c16dff9119dfa

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - pymbar <4.0.0

test:
  imports:
    - physical_validation
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/shirtsgroup/physical_validation
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Physical validation of molecular simulations
  description: |
    physical_validation is a package aimed at testing results obtained by molecular dynamics
    simulations for their physical validity.
  doc_url: http://physical-validation.readthedocs.io/
  dev_url: https://github.com/shirtsgroup/physical_validation

extra:
  recipe-maintainers:
    - mattwthompson
    - ptmerz
